### PR TITLE
Add catch handler to acquireTokenSilent method so that the promise will be rejected up the chain

### PR DESCRIPTION
**Pull request by freeman-g**
I had an issue where acquireTokenSilent failed and I was not able to catch that error because the aquireTokenSilent method itself never rejected the promise. I have updated the commonjs and es6js files to fix this issue in this pull request.

-----------------------------------

Add catch handler to acquireTokenSilent method so that the promise will be rejected up the chain and callers of this function will be able to
implement their own error handling.

Prior to this change, a caller of acquireTokenSilent could not catch
certain errors and would receive an "uncaught (in promise)" error

### CODE REVIEW

**Comment by rohitnarula7176** [comment]
@freeman-g Thank you for your contribution. Can you please make the changes in the UserAgentApplication.ts under the src folder in the repo and resubmit the pull request. The common-js and es-6 files will be updated accordingly when you npm run build command.

**Comment by freeman-g** [comment]
@rohitnarula7176 - thanks, I updated the TypeScript file and run `npm run build` to update the JS files and then pushed a new commit.

**Comment by rohitnarula7176** [comment]
@freeman-g Thank you for your contribution. The pull request shows a bunch of line deletions and additions and which makes it difficult to analyse the actual code changes. Would you be okay if I just add the catch handler myself to the functions that return a promise in UserAgentApplication.ts.

**Comment by freeman-g** [comment]
@rohitnarula7176 sounds good to me. I have format-on-save turned on in VSCode, so that may have changed some of those lines. At the end of the day, I just added the following to acquireTokenSilent:

```
                return _this.authorityInstance.ResolveEndpointsAsync()
                    .then(function () {
                        // refresh attept with iframe
                        //Already renewing for this scope, callback when we get the token.
                        if (_this._activeRenewals[scope_1]) {
                            _this._logger.verbose("Renew token for scope: " + scope_1 + " is in progress. Registering callback");
                            //Active renewals contains the state for each renewal.
                            _this.registerCallback(_this._activeRenewals[scope_1], scope_1, resolve, reject);
                        }
                        else {
                            if (scopes && scopes.indexOf(_this.clientId) > -1 && scopes.length === 1) {
                                // App uses idToken to send to api endpoints
                                // Default scope is tracked as clientId to store this token
                                _this._logger.verbose("renewing idToken");
                                _this.renewIdToken(scopes, resolve, reject, userObject_1, authenticationRequest_1, extraQueryParameters);
                            }
                            else {
                                _this._logger.verbose("renewing accesstoken");
                                _this.renewToken(scopes, resolve, reject, userObject_1, authenticationRequest_1, extraQueryParameters);
                            }
                        }


    // add this part
                    }).catch((err) => {
                        reject(err)
                    });
```

**Pull request closed without merging**
