### PR TITLE
Support for renewing multiple asynchronous requests

### PR DESCRIPTION
**Pull request by austindyoung**
This PR resolves issue #73.

In this PR, `UserAgentApplication.registerCallback` selects a representative request state and associates it with the collection of all token renewal `PromiseLike<string>` values belonging to the same scope and token type.

Subsequently, one iframe request is made per collection.

Note: the nonce token assignments in `UserAgentApplication.renewToken` and `UserAgentApplication.renewIdToken` in this PR are conditional depending on whether the current renewal request is the representative.

### CODE REVIEW

**Comment by brianfoody** [comment]
@austindyoung did you make any progress with getting this merged? Have run across this issue as well.

**Comment by gramidt** [comment]
Could we get an update when this will be merged back in? Also, when is the next version going to be deployed?

**Comment by rohitnarula7176** [comment]
@brianfoody @gramidt I cannot merge this pull request as I think there was a minor change required in the library to fix this issue and I have made that change in my branch. Can you please use my branch https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/rohitnarula7176/Issue_73
and confirm if it resolves your issue. We will be releasing a new version of the library early next week with the fix.

**Comment by gramidt** [comment]
Thanks @rohutnarula7176! We'll try to test it out today, and respond with the results. For next weeks release, what all fixes will be in it?

**Comment by rohitnarula7176** [comment]
@gramidt We will add all the fixes in the change log but the major ones will be a bug that was related to the renewal of idToken and supporting asynchronous token renewal requests.

**Comment by rohitnarula7176** [comment]
@gramidt Did you get a chance to test my branch https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/rohitnarula7176/Issue_73 to confirm if the issue with multiple asynchronous acquireToken requests is resolved for you.

**Comment by gramidt** [comment]
Unfortunately we haven’t got it working yet. Spent some time on it, but
after switching to either your branch for the PR or the dev branch, our app
continually reloads. Once we solve that, we should be able to test your
change.

**Comment by gramidt** [comment]
I'm hoping we can get back to solving our reloading issue today, so we can verify this fix.

**Pull request closed without merging**
