### PR TITLE
sets homeAccountIdentifier to idTokenObj.claims.sub for AD FS workflo…

### LINKED ISSUE #2532: acquireTokenSilent doesn't work for AD FS workflow
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.5.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

User successfully acquired accessToken and refresh token, but there is no client_info in the response
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fef918b8cdbff3dc82aea3ca41118a0130ac1d40/lib/msal-common/src/response/ResponseHandler.ts#L115
so homeAccountId will stay empty on the other hand we set homeAccountId on the account here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fef918b8cdbff3dc82aea3ca41118a0130ac1d40/lib/msal-common/src/cache/entities/AccountEntity.ts#L183

later when I'm trying to refresh token it's not possible to get refreshToken from the storage, as there is no homeAccountId associated with it

So proposal is to do the same as we do for account, set it from `idTokenObj.claims.sub` for AD FS workflow.

Thoughts? I'll create PR...

### PR DESCRIPTION
**Pull request by MariMax**
…w, fixes #2532

### CODE REVIEW

**Comment by jasonnutter** [comment]
I believe will be addressed in #2516. Can you please take a look at that PR?

**Comment by MariMax** [comment]
I doubt #2516 will help problem is acquireTokenSilent cannot find details in cache, because it trying to get it based on 
account.homeAccountId and account.environment see here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/29c5e1a46f8ac4265a96070d5a50222763c2b211/lib/msal-common/src/cache/CacheManager.ts#L542

fixing localAccountId won't help in this case

**Comment by sameerag** [comment]
Thank you for this @MariMax. We made changes for #2516 to add this use case. I just pushed the changes, introduced a centralized helper API to generate `homeAccountId`. Can you please check that?

**Comment by MariMax** [comment]
@sameerag yep that should work, thank you!
handled in #2516 closing

**Pull request closed without merging**
