### PR TITLE
[msal-react] adding new sample with class components

### PR DESCRIPTION
**Pull request by derisen**
This PR adds a new sample to msal-react demonstrating the usage of class components.

This is a conversion of the current [msal-react quickstart sample](https://github.com/Azure-Samples/ms-identity-javascript-react-spa).

Refers to: #2965
Closes: [#2933](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2933)

### CODE REVIEW

**Comment by tnorling** [comment]
@derisen I was thinking about this last night and I think actually what I would suggest instead of a standalone sample is to add a page to the existing [react-router-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) that demonstrates using a class component. I can work on porting your changes here over to that sample

**Comment by derisen** [comment]
@tnorling aah, that makes sense too (I've missed that sample). Ok then, I'll leave the decision to you. I can certainly add a new page there with classes (a 'mails' page perhaps?)

**Comment by tnorling** [comment]
> @tnorling aah, that makes sense too (I've missed that sample). Ok then, I'll leave the decision to you. I can certainly add a new page there with classes (a 'mails' page perhaps?)

@derisen I'd suggest just duplicating the /profile page but re-implement as a class component so that it's easy to compare the 2. Our microsoft accounts don't have consent to the Mail.Read scope making testing more challenging for the mail stuff unfortunately.

**Comment by derisen** [comment]
> > @tnorling aah, that makes sense too (I've missed that sample). Ok then, I'll leave the decision to you. I can certainly add a new page there with classes (a 'mails' page perhaps?)
> 
> @derisen I'd suggest just duplicating the /profile page but re-implement as a class component so that it's easy to compare the 2. Our microsoft accounts don't have consent to the Mail.Read scope making testing more challenging for the mail stuff unfortunately.

Sounds good!

**Comment by derisen** [comment]
Closed by #2973

**Pull request closed without merging**
