### PR TITLE
fix: update to angular7 and rxjs6

### PR DESCRIPTION
**Pull request by zamzowd**
Since there's hesitation to accept #524 this pull request has only the
minimal updates to update the packages.

### CODE REVIEW

**Comment by pfleenor** [comment]
Can some please merge this?

**Comment by dotnetcanuck** [comment]
Is there an updated timeline on when a version 1.0.x might be available? Or could this PR be merged as a temporary Preview version?

**Comment by sameerag** [comment]
We are working on the planning right now and will release the updated timeline.  Apologies for the delay, this is an activity we want to get to as soon as we can. 

cc @jasonnutter @DarylThayil Is there merit in pulling in this change for temporary preview? My only concern was if this breaks existing angular for some users.

**Comment by zamzowd** [comment]
@dotnetcanuck it might be worthwhile to get the latest MSAL core and write your own Angular implementation.  You just need a Service that initiates and holds the authentication (houses a private UserAgentApplication), a Guard to require authentication for specified routes, and an Interceptor to get the token from the service and use it in HTTP requests to specified domains.

**Comment by jasonnutter** [comment]
Closing, as we will be working this quarter to upgrade msal-angular to support the newer version of Angular.

**Comment by dotnetcanuck** [comment]
@zamzowd That's what we ended up doing.

To put it bluntly, we found the stock Angular wrapper is severely lacking in several areas.

**Pull request closed without merging**
