### PR TITLE
Add Node 16 to msal-node supported versions

### PR DESCRIPTION
**Pull request by jasonnutter**

### CODE REVIEW

**Review by tnorling — APPROVED** [review]

**Comment by sameerag** [comment]
I want the samples tested on `node 16` before we release this. Let me know if you need any help, me or @samuelkubai can pitch in.

**Comment by hectormmg** [comment]
> I want the samples tested on node 16 before we release this. Let me know if you need any help, me or @samuelkubai can pitch in.

@sameerag the way the E2E tests are set up, adding the Node version to the workflow, as this PR does, automatically runs the E1E tests for that version, so at least the automated E2E tests are covered here.

**Review by hectormmg — APPROVED** [review]
LGTM

**Comment by jasonnutter** [comment]
> > I want the samples tested on node 16 before we release this. Let me know if you need any help, me or @samuelkubai can pitch in.
> 
> @sameerag the way the E2E tests are set up, adding the Node version to the workflow, as this PR does, automatically runs the E12E tests for that version, so at least the automated E2E tests are covered here.

@sameerag @hectormmg Yeah, I was relying on the E2E tests here.

**Comment by sameerag** [comment]
> > > I want the samples tested on node 16 before we release this. Let me know if you need any help, me or @samuelkubai can pitch in.
> > 
> > 
> > @sameerag the way the E2E tests are set up, adding the Node version to the workflow, as this PR does, automatically runs the E12E tests for that version, so at least the automated E2E tests are covered here.
> 
> @sameerag @hectormmg Yeah, I was relying on the E2E tests here.

In that case, yes. Approving.

**Review by sameerag — APPROVED** [review]

**Pull request merged**
