### PR TITLE
Add support for redirectUri as a function

### LINKED ISSUE #458: Redirect URI incompatibility with HTML5 history API
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 69.0.3497.100
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3
</code></pre>

## Current behavior

When the `Msal.UserAgentApplication` loads, it appears to determine the redirect URI (if not specified in the options) by using `window.location.href`.

However, if the HTML5 history API is subsequently used to modify the browser location, and then the loginPopup is initiated, the redirect URI is set to the original value at the time of construction of `Msal.UserAgentApplication`, and not the current window location.

This is very surprising (and wrong) behavior.

## Expected behavior
The expected behavior would be for the redirect URI to match the current window location, unless explicitly set at construction time. Also, for maximum flexibility, I would allow redirectURI option to also be a function -- and the default implementation to be to determine the *current* window.location.href at the time of the login call. Making it a function allows the user to provide their own logic though, and deep integration with their own code.

## Minimal reproduction of the problem with instructions

1. Create an Msal.UserAgentApplication at page '/'
2. Use the history.push API to change the page to '/foo'
3. Initiate a loginPopup call

### PR DESCRIPTION
**Pull request by emilpalsson**
Set default redirectUri/postLogoutRedirectUri to a function returning
the current location.href, instead of the location.href from when the
UserAgentApplication was instantiated. Enables use of history.pushState.

One test updated, and tests added for redirectUri/postLogoutRedirectUri
as functions.

Closes #458.

### CODE REVIEW

**Comment by jabbera** [comment]
Is there any change of this getting merged? It's a pain and I don't want to have to maintain another patch file like I do for angular 6

**Comment by jclapadula** [comment]
Hi,
If I'm not wrong this change made our application to fail when the first token was expired.

Before this PR the default redirectUri was 
`window.location.href.split("?")[0].split("#")[0]`
which is the location corresponding to the instantiation of the UserAgentApplication, in our case the only redirectUri in our App registration (.../login).

Now the default value is 
`() => window.location.href.split("?")[0].split("#")[0]`
which corresponds with the current location, the login location the first time and something different every other time. Of course we don't have all the possible URIs set as redirect URIs in our app registration.

As workaround we will explicitly set the login page when instantiating UserAgentApplication, but I think it's quite probable that some other people is having this error.

Regards

**Comment by rocketraman** [comment]
@jclapadula The configured redirect_uri does not have to exactly match one of the redirect_uris registred in the portal, just the origin. e.g. https://example.com/my/random/path is a valid client redirect_uri when the registered redirect_uri is https://example.com. See the discussion in the original issue.

It's likely all you need to do is configure your `redirect_uri` to just the origin, and it should work for all cases.

**Comment by rocketraman** [comment]
@jclapadula et al

I've raised an issue with Azure support, and what they are telling me is that the comparison against the exact URI is the current expected behavior. Therefore, I doubt this will change any time soon. If anyone wants the old behavior, I believe you can achieve it with the following setting:

`redirectUri: window.location.origin`

In addition, if you want to support linking directly to an internal route in your SPA application:

`navigateToLoginRequestUrl: false`

so that MSAL doesn't try to navigate directly to the URL itself, but instead allows your SPA app to use its internal routing mechanism after the login is complete.

I believe the functionality added via this pull request may still be useful in some cases, but because of the exact URI comparison, but I suspect the default value used for `redirectUri` should be reverted.

**Pull request merged**
