### PR TITLE
[msal-browser] Export TokenResponse at top level

### PR DESCRIPTION
**Pull request by HarryGifford**
`TokenResponse` is a return type and argument type from a few `PublicClientApplication` methods.

### CODE REVIEW

**Review by DarylThayil — APPROVED** [review]
@pkanher617  thoughts?

**Review by jasonnutter — APPROVED** [review]

**Comment by HarryGifford** [comment]
@jasonnutter, @DarylThayil for some reason coveralls doesn't execute for me:
image
The [code coverage step](https://dev.azure.com/identitydivision/Engineering/_build/results?buildId=521508&view=logs&j=2967aab0-cd39-5001-1200-3620872fc729&t=0cc911ac-eae8-5138-7a44-3758c1f3cf06&l=34) fails saying "Couldn't find a repository matching this job."

**Comment by jasonnutter** [comment]
@HarryGifford Yeah, coverage doesn't work at forks, we're going to turn it off for forks soon to mitigate those errors.

**Comment by pkanher617** [comment]
@HarryGifford I've made these changes in PR #1584, once that PR is merged TokenResponse will be exported.

**Pull request closed without merging**
