### PR TITLE
clientSecret can now (once again) be provided as undefined

### LINKED ISSUE #7201: setClientCredential() errors when no `clientCertificate` property is set
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.11.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

[This commit](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/2ff18f23f0631507ccbf966478b152b02c9d25af) stops checking if `config.auth.clientCertificate` is actually defined.
CC: @Robbie-Microsoft 

### Error Message

TypeError: Cannot read properties of undefined (reading 'thumbprint')

### MSAL Logs

_No response_

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
auth: {
    authority: 'url',
    clientId: 'guid',
    clientSecret: 'secret',
}
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

Try authenticating without setting the `clientCertificate` property in the `auth`

### Expected Behavior

Auth using `clientSecret`

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

2.10.0

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by Robbie-Microsoft**
Fixed a regression accidentally introduced in [Implemented SHA2 Certificate Functionality](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/7192). `clientSecret` can now (once again) be provided as `undefined`.

added unit test

### CODE REVIEW

**Comment by yuezk** [comment]
Hi,

I'm from #7201 and am curious about the root cause since the code has been strongly typed.

Looks like this is a runtime error and the root cause is as @RoelVB said in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/7201#issuecomment-2232474139.

Though this PR can fix #7201, I'm afraid we may run into similar issues if it is not fixed from the root.

Related:
- https://github.com/microsoft/TypeScript/issues/44432
- https://github.com/microsoft/TypeScript/issues/57408

**Review by maorleger — APPROVED** [review]
We chatted offline a bit. Here's what I think:

- Agree that there's a larger issue here with the spread operator. There is always a disconnect between your defined types and what you actually get at runtime especially when it comes to your external API
- IMO, fixing this correctly requires some additional thought. While I agree that you _could_ fix the cert key specifically by spreading it out ala `clientCertificate: { ...DEFAULT_AUTH_OPTIONS.clientCertificate, ...auth.clientCertificate } },` that still requires discipline whenever objects are added to the config and is an easy trap to fall into. Consider creating a separate issue to track the larger fix and linking to it in your PR
- You may also play around with [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes) which may not help your users but it will help you catch errors internally where possible [like this playground](https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true#code/C4TwDgpgBAsiDyAjAVhAxsKBeKBvAUFEVAIYD8AXFAHYCuAtohAE4A0hxilNDTz+AX3z40Ae2oBnTABMIAMxK0ANsAnY8HIiSoBWdsSiIqANkHCxkzCQy0SSiVThJUGIjgIHtUWtVlyAltQQ0lBmIuISokoQAHRKogDmABS4MWl+iioSrFBpMbikVD5+gcFQAgIAlOGSUbHxyanp8pmqOXkFFZVAA) - again, it's not perfect especially with spread
- I would also check if `config.auth.clientCertificate` is used anywhere else in the code just to confirm

LGTM for the immediate future, and a separate issue can be created to address the troubles with the spread operator here. That's at least what I would do!

**Comment by Robbie-Microsoft** [comment]
Thanks @maorleger!

@RoelVB I agree with your analysis about what the root cause is. However, this behavior (root cause) already existed before the regression this PR addresses was introduced. 

@yuezk I'm going to keep this PR as is, and create a new GitHub issue for "larger refactoring to remove the ambiguity for deeply nested properties".

**Comment by yuezk** [comment]
Thanks for explaining this. I agree with your decision.

**Review by neha-bhargava — APPROVED** [review]

**Comment by Robbie-Microsoft** [comment]
[Linking the issue I created.](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/7221)

**Review by bgavrilMS — APPROVED** [review]

**Pull request merged**
