### PR TITLE
Update tests and docs for AzureCloudInstance support

### PR DESCRIPTION
**Pull request by sameerag**

### CODE REVIEW

**Comment by jasonnutter** [comment]
I just see docs, are there tests coming as well?

**Review by Robbie-Microsoft — APPROVED** [review]

**Comment by peterzenz** [comment]
> I just see docs, are there tests coming as well?

@sameerag I'm assuming this is still a draft or is incomplete?

**Comment by derisen** [comment]
adding a reminder for linking & updating the [authority doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/authority.md) here

**Comment by sameerag** [comment]
Closed. Will update for 3.x as applicable.

**Comment by sameerag** [comment]
Abandoning to be updated for 3.x

**Pull request closed without merging**
