### PR TITLE
Correct spelling mistake for 0.x-1.x-upgrade-guide.md

### PR DESCRIPTION
**Pull request by wmundev**
Correcting a spelling mistake

### CODE REVIEW

**Review by jasonnutter — APPROVED** [review]

**Review by jo-arroyo — APPROVED** [review]

**Comment by jo-arroyo** [comment]
@wmundev Thanks for your contribution! Could you please run `npm run beachball:change` in the root directory and go through the prompts to generate the change files? You can select change type "None".

Thanks!

**Comment by wmundev** [comment]
all done, ready to merge whenever :)

**Comment by wmundev** [comment]
sorry had to force push to get rid of my private email address, should be good now

**Comment by tnorling** [comment]
@wmundev Can you remove the change files for everything except msal-angular? Not sure why beachball prompted you for the other libs...

**Pull request merged**
