### PR TITLE
adding CacheLocationChoices so clients don't need to worry about type widening

### PR DESCRIPTION
**Pull request by jodonnell**

### CODE REVIEW

**Comment by jodonnell** [comment]
running npm run endToEnd was broken, npm run test failed one time and passed the next, so seems like there might be a flaky test?

i didn't want to change CacheLocation since probably a lot of users are relying on that so I just added a new enum that can be used instead.

**Comment by sameerag** [comment]
Merging as we got the team's approval.

**Comment by pkanher617** [comment]
This ended up breaking surface configuration for cacheLocation, we will revert this PR and revisit the change in a future release.

**Comment by pkanher617** [comment]
@jodonnell This was failing  in typescript because it did not allow users to set string values for localstorage and sessionstorage and the enums weren't exported. Could you please test this in typescript and javascript to ensure the behavior is working correctly? You can open another PR, unfortunately I can't reopen this one.

**Comment by jodonnell** [comment]
I will try to get this done in the near future.

**Pull request merged**
