### PR TITLE
Remove generated doc files from repo, deploy them to Github Pages

### PR DESCRIPTION
**Pull request by jasonnutter**
These were creating a lot of churn in our PRs, so I've removed from the repo, and have them generated and pushed to Github Pages.

https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/index.html

### CODE REVIEW

**Comment by jasonnutter** [comment]
I'll keep this as a manual step, for now. We can look at putting it into CI in a follow up PR.

**Comment by jasonnutter** [comment]
Further follow up work will include adding lint rules to require JS Doc comments.

**Review by jmckennon — APPROVED** [review]
Awesome change, LGTM

**Review by DarylThayil — APPROVED** [review]
big fan

**Pull request merged**
