### PR TITLE
Express MVC web app using MSAL Node

### PR DESCRIPTION
**Pull request by derisen**
This PR contains an express.js MVC web app secured with msal-node. There are two parts of interest:

* `src/AuthProvider.ts` - a simple wrapper around msal-node `confidentialClientApplication` handling login, logout and token acquisition in both AAD and B2C
* `TestApp/` - sample express application authenticating with Azure AD and calling Graph API

Please see the README for more information. Merging this would validate the approach and unblock the [MSAL Node web app chapterwise tutorial](https://github.com/Azure-Samples/ms-identity-javascript-nodejs-tutorial), as well as providing an example for docs.microsoft.

Might help with #3151 

p.s. doesn't contain any tests at the moment but I'm planning to add them in a future PR.

### CODE REVIEW

**Comment by kwoxer** [comment]
Your URL does not work. Could you repair it? Thx.

**Comment by derisen** [comment]
> Your URL does not work. Could you repair it? Thx.

@kwoxer sorry, can you mention which URL?

**Comment by jasonnutter** [comment]
@derisen What is the status of this PR?

**Comment by derisen** [comment]
> @derisen What is the status of this PR?

@jasonnutter will remove the extra logic for handling B2C password-reset user flow (now that password-reset is integrated), and find out why E2E tests for Node 14 fails. Should be done in a day or two.

**Review by hectormmg — APPROVED** [review]
Sample looks great! Thanks @derisen !

**Review by samuelkubai — APPROVED** [review]

**Pull request merged**
