### PR TITLE
update 'passport' version

### PR DESCRIPTION
**Pull request by sameerag**
Update [`passport`](https://www.npmjs.com/package/passport) to latest version [`0.6.0`](https://www.npmjs.com/package/passport/v/0.6.0)

Upgrade recommended [here](https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d)

### CODE REVIEW

**Review by peterzenz — APPROVED** [review]

**Comment by tnorling** [comment]
Any breaking changes between 0.4.x and 0.6.x we need to address?

**Comment by sameerag** [comment]
> Any breaking changes between 0.4.x and 0.6.x we need to address?

Not as far as I know. I am checking the package dependencies but all unit tests pass. Yet to do E2E, as far as I know, they do not exist in the pipeline.

**Comment by tnorling** [comment]
@sameerag Also look at #4993 which makes a similar change

**Comment by jasonnutter** [comment]
@sameerag Can you please also add a changelog entry (done manually).

**Review by jasonnutter — APPROVED** [review]

**Comment by YaakovR** [comment]
@sameerag I'm looking to move away from this package, since it is in maintenance mode. Do you know what new module I should be using instead?

**Comment by jasonnutter** [comment]
> > Any breaking changes between 0.4.x and 0.6.x we need to address?
> 
> Not as far as I know. I am checking the package dependencies but all unit tests pass. Yet to do E2E, as far as I know, they do not exist in the pipeline.

Doesn't look like there are any relevant breaking changes, based on the changelog https://github.com/jaredhanson/passport/blob/master/CHANGELOG.md

**Comment by sameerag** [comment]
> 

@YaakovR we are currently working on a `node-token-validation` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/node-token-validation). Please watch out for our release announcement for the same. 

cc @jo-arroyo @EmLauber

**Comment by sameerag** [comment]
> @sameerag I'm looking to move away from this package, since it is in maintenance mode. Do you know what new module I should be using instead?

> 

@YaakovR we are currently working on a `node-token-validation` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/node-token-validation). Please watch out for our release announcement for the same. 

cc @jo-arroyo @EmLauber

**Review by jasonnutter — APPROVED** [review]

**Comment by sameerag** [comment]
> > @sameerag I'm looking to move away from this package, since it is in maintenance mode. Do you know what new module I should be using instead?
> 
> > 
> 
> @YaakovR we are currently working on a `node-token-validation` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/node-token-validation). Please watch out for our release announcement for the same.
> 
> cc @jo-arroyo @EmLauber

slight correction: There is a new team which is picking up the node-token-validation library. Please watch out this space for more clarity. cc @bgavrilMS @jmprieur for tracking this later.

**Comment by jeffwilcox** [comment]
Anyone hitting issues here? In our project for some reason, this library is still pulling in an older `passport` dependency, which with the breaking change in `req.logout` is a bit tough to reason through. (Happy to hear this is user error though... investigating)

**Comment by YaakovR** [comment]
> > > @sameerag I'm looking to move away from this package, since it is in maintenance mode. Do you know what new module I should be using instead?
> > 
> > 
> > > 
> > 
> > 
> > @YaakovR we are currently working on a `node-token-validation` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/node-token-validation). Please watch out for our release announcement for the same.
> > cc @jo-arroyo @EmLauber
> 
> slight correction: There is a new team which is picking up the node-token-validation library. Please watch out this space for more clarity. cc @bgavrilMS @jmprieur for tracking this later.

@sameerag Is there any updates on this?

**Comment by jmprieur** [comment]
We have a solution for first party partners. We are working on a solution for third party customers.
@YaakovR would you like to meet to discuss our solution? If that's the case, would you like to send me an email to Jean-Marc.Prieur at Microsoft dot com?

Thanks!

**Pull request merged**
