### PR TITLE
Fix addEventCallback input parameter type

### LINKED ISSUE #6309: PublicClientApplication.addEventCallback has incorrect callback type
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

The type for for the `callback` parameter in `PublicClientApplication.addEventCallback` used to be typed as `EventCallbackFunction` now it is typed as `Function`

### Error Message

_No response_

### Msal Logs

_No response_

### MSAL Configuration

```javascript
Not a configuration issue
```

### Relevant Code Snippets

```javascript
msalInstance.addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
    console.log('login success');

    const account = (event.payload as AuthenticationResult).account;
    msalInstance.setActiveAccount(account);
  }
});
```

### Reproduction Steps

1. Update to v3.0.0
2. Try to `addEventCallback` on the `PublicClientApplication`
3. Typescript no longer has parameter information for the `EventMessage`

### Expected Behavior

Typescript should have the correct type for the callback parameters

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser 2.38.0

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by tnorling**
Fixes input parameter type for addEventCallback which broke when moving from v2 to v3

Addresses #6309

### CODE REVIEW

**Review by sameerag — APPROVED** [review]

**Comment by sameerag** [comment]
Can we add tests to match the type?

**Review by peterzenz — APPROVED** [review]
Anything we can do to properly test for this?

**Review by lalimasharda — APPROVED** [review]

**Review by jo-arroyo — APPROVED** [review]
Thanks for this fix, Thomas!

**Comment by tnorling** [comment]
Generally speaking testing types is done by the TypeScript compiler, you can't really write unit tests against non-primitive types because types are stripped at runtime. Functionally nothing changes here, this is purely a TypeScript change.

We do have tests for the `addEventCallback` API, however, they continued to pass because PCA was expecting a _less specific_ type. Now that we've restored the expectation for a _more specific_ type attempts to pass in a less specific type would fail at the TypeScript level.

**Pull request merged**
