### PR TITLE
fix the UTF-16 encoding problem

### PR DESCRIPTION
**Pull request by Davilink**
Use the solution found in the jwt-decode.js file of the jwt.ms website.

#264

### CODE REVIEW

**Comment by kosjanne** [comment]
Pretty sad that this didn't make it to 1.0 version. Official msal 1.0 is now basically for people with American names only. There seems to be one Travis test failing in this Pull Request. Does this mean that until @Davilink fixes that test, we won't get support for non-american characters for msal?

**Comment by sameerag** [comment]
@kosjanne we will try make the next patch/minor release asap. We are internally aligning with some policy for encode decode to be able to use a more generic library. This is one of the top issues that will be addressed in the followup release.

**Comment by Davilink** [comment]
I would like to fix the PR but i don't know where to start to fix the tests

**Comment by sameerag** [comment]
@Davilink  as I said it is not about the tests. We are discussing to check if we can use a standardized library for this decoding. Any tests, we will take care of them.

**Comment by sameerag** [comment]
@Davilink @kosjanne can one of you please try this PR #712 and confirm it it fixes your issue? We plan to merge this post testing.

**Comment by Davilink** [comment]
Sadly, i'm not working anymore on the project that needed that fix, so i would not know how to test quickly

**Pull request closed without merging**
