### PR TITLE
Restore error codes for acquireTokenSilent telemetry

### PR DESCRIPTION
**Pull request by jasonnutter**
This was mistankely removed in https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4973/files#diff-827dd2c804974fc1c04ca2f8fa2372b1d42f06b7d0c248f0b390da147e208931L137-L138

### CODE REVIEW

**Review by tnorling — APPROVED** [review]

**Comment by tnorling** [comment]
Should we include tests to make sure this doesn't happen again?

**Comment by jasonnutter** [comment]
> Should we include tests to make sure this doesn't happen again?

Yeah, probably a good idea.

**Review by peterzenz — COMMENTED** [review]
We definitely need a test for this.

**Comment by jasonnutter** [comment]
@peterzenz @tnorling Tests added for perf event properties included for acquireTokenSilent.

**Review by peterzenz — APPROVED** [review]

**Comment by bmahall** [comment]
@jasonnutter Thanks for restoring this!

**Pull request merged**
