### PR TITLE
fix: AzureAD/microsoft-authentication-library-for-js#2652

### PR DESCRIPTION
**Pull request by restfulhead**
Fixes  https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2652

`async` was missing and the test mock returned `null` instead of a Promise of `null`.

### CODE REVIEW

**Review by tnorling — APPROVED** [review]

**Review by pkanher617 — APPROVED** [review]

**Comment by pkanher617** [comment]
@restfulhead before this is merged, could you try running `npm run beachball:change` at the root of the repository? It will ask you for a few prompts to create a changefile, this will allow us to add this to our changelog automatically. We will make sure to enforce this as a check for forked PRs soon.

**Comment by jasonnutter** [comment]
Thanks for the PR! I'll add a lint rule to enforce that all promises are awaited, to help avoid this sort of bug in the future.

**Review by sameerag — APPROVED** [review]

**Comment by restfulhead** [comment]
@pkanher617 I ran `npm run beachball:change`. There was an error at the end where the commit failed ("error: gpg failed to sign the data"). So I manually committed the generated change file. Does this look good on your end?

**Comment by pkanher617** [comment]
> @pkanher617 I ran `npm run beachball:change`. There was an error at the end where the commit failed ("error: gpg failed to sign the data"). So I manually committed the generated change file. Does this look good on your end?

Looks perfect, thanks!

**Pull request merged**
