### PR TITLE
Minor correction to grammar in docs

### PR DESCRIPTION
**Pull request by iambmelt**
Corrects a grammatical error in `SsoSilentRequest.ts` typedocs

### CODE REVIEW

**Comment by iambmelt** [comment]
Just something I spotted while perusing your APIs 😉

**Comment by iambmelt** [comment]
Looks like a `beachball-check` failed in CI... do I need to run this for a docs contribution?

**Comment by iambmelt** [comment]
Does this documentation need to updated to include params for `pop` flows?
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/5b350a5f97b43e1a5a87153bb4a13632f7c615b9/lib/msal-browser/docs/access-token-proof-of-possession.md#at-pop-request-parameters

**Review by jasonnutter — APPROVED** [review]

**Comment by jasonnutter** [comment]
> Does this documentation need to updated to include params for `pop` flows? https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/5b350a5f97b43e1a5a87153bb4a13632f7c615b9/lib/msal-browser/docs/access-token-proof-of-possession.md#at-pop-request-parameters

Thanks! And yes, they need to be completely redone to be proper typedoc comments so that they don't get removed. We'll make sure that addressed then.

**Review by tnorling — APPROVED** [review]

**Comment by tnorling** [comment]
> Looks like a `beachball-check` failed in CI... do I need to run this for a docs contribution?

Beachball isn't smart enough to understand that you only changed a comment, rather than code. Since you edited a `.ts` file it wants a changefile to go with it. You can specify change type 'none' for this case

**Comment by iambmelt** [comment]
> 

Done. Feel free to merge this PR when if you're happy with the state 😄

**Review by sameerag — APPROVED** [review]

**Comment by iambmelt** [comment]
🎉

**Pull request merged**
