### PR TITLE
Add asynchronous initialisation

### PR DESCRIPTION
**Pull request by vlafranca**
MSAL & MSAL-ANGULAR
#1665 

Add ability to initialize MsalModule asynchronously by adding configure method (retroactive with old initialisation in constructor).

### CODE REVIEW

**Comment by vlafranca** [comment]
I can't see the build error, on my machine the build is working fine. If anyone can give me more detail I would be glad to fix this.

**Comment by jasonnutter** [comment]
> I can't see the build error, on my machine the build is working fine. If anyone can give me more detail I would be glad to fix this.

This is likely due to our CI not properly supporting forks, which were working on addressing. We'll let you know if we need any changes regarding the build.

**Comment by vlafranca** [comment]
> > I can't see the build error, on my machine the build is working fine. If anyone can give me more detail I would be glad to fix this.
> 
> This is likely due to our CI not properly supporting forks, which were working on addressing. We'll let you know if we need any changes regarding the build.

Ok thanks for your answer. I will wait for some news from you.

**Comment by ursedaniel** [comment]
Hello, any news into this? It's a really good functionality and we really need it for our project, thanks!

**Comment by Gillardo** [comment]
Has this functionality been enabled?

**Pull request closed without merging**
