### PR TITLE
Scope beachball to lib folder

### PR DESCRIPTION
**Pull request by tnorling**
When we bump versions before publish beachball also bumps dependencies in the `package.json` files in the samples directory. This is undesirable as samples are no longer in scope for lerna and our E2E tests need to reference local builds. This PR scopes beachball  commands to only affect the `lib` directory.

Please callout other samples that should be updated to pull packages locally instead of from npm

### CODE REVIEW

**Review by hectormmg — APPROVED** [review]

**Comment by pkanher617** [comment]
> Please callout other samples that should be updated to pull packages locally instead of from npm

I think this will require changes to all packages that are referencing MSAL.js packages from npm. So, every node sample, the browser Typescript sample, etc.

**Comment by hectormmg** [comment]
> > Please callout other samples that should be updated to pull packages locally instead of from npm
> 
> I think this will require changes to all packages that are referencing MSAL.js packages from npm. So, every node sample, the browser Typescript sample, etc.

I see why samples used in end-to-end tests need to use the local versions, but I think the standalone node usage samples can use the latest published package.

**Comment by sameerag** [comment]
My two cents: In Philosophy, yes, standalone samples can use the published version. However, since node e2e isn't robust yet, can we retain the ability to test locally for the standalone samples for now? cc @hectormmg

**Comment by pkanher617** [comment]
> > > Please callout other samples that should be updated to pull packages locally instead of from npm
> > 
> > 
> > I think this will require changes to all packages that are referencing MSAL.js packages from npm. So, every node sample, the browser Typescript sample, etc.
> 
> I see why samples used in end-to-end tests need to use the local versions, but I think the standalone node usage samples can use the latest published package, so I think msal-node is covered here.

It does make local dev a little more challenging because we can't run samples based on local packages anymore (since samples are being removed from lerna). If the samples used in e2e tests can be run locally it should be fine.

**Comment by tnorling** [comment]
> It does make local dev a little more challenging because we can't run samples based on local packages anymore (since samples are being removed from lerna). If the samples used in e2e tests can be run locally it should be fine.

To be clear the samples have already been removed from lerna, it was done a while back. This PR is just stopping beachball from overwriting the local file with the published version when we run beachball:bump (breaking e2e tests)

**Review by pkanher617 — APPROVED** [review]

**Review by sameerag — APPROVED** [review]

**Comment by jasonnutter** [comment]
> > It does make local dev a little more challenging because we can't run samples based on local packages anymore (since samples are being removed from lerna). If the samples used in e2e tests can be run locally it should be fine.
> 
> To be clear the samples have already been removed from lerna, it was done a while back. This PR is just stopping beachball from overwriting the local file with the published version when we run beachball:bump (breaking e2e tests)

My understanding is that the samples were only not in scope for the `lerna run` command, but are still in scope for `lerna bootstrap`. Not sure if that changes anything about this PR.

**Review by jasonnutter — APPROVED** [review]

**Comment by tnorling** [comment]
> My understanding is that the samples were only not in scope for the `lerna run` command, but are still in scope for `lerna bootstrap`. Not sure if that changes anything about this PR.

We should test this but I think it's out of scope for both. We removed it from scope to make build faster since running `npm install` from the root of the repo was installing sample dependencies (puppeteer takes over a full minute by itself)

**Pull request merged**
