### PR TITLE
Update ProtectedResourceScopes type to allow unprotected resource for…

### PR DESCRIPTION
**Pull request by budmil**
… concrete request type

In the Interceptor documentation (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md), it is stated that it should be possible to use scope value 'null' to indicate that the resource should be unprotected, even only for the concrete request type. This Pull requests ensures that the typing follows such logic.

### CODE REVIEW

**Comment by derisen** [comment]
@budmil thanks for catching this -could you please go through [beachball check](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md#beachball-check)

**Comment by budmil** [comment]
@microsoft-github-policy-service agree [company="freiheit.software"]

**Comment by budmil** [comment]
@microsoft-github-policy-service agree company="freiheit.software"

**Review by derisen — APPROVED** [review]

**Review by jo-arroyo — APPROVED** [review]

**Comment by derisen** [comment]
@budmil closing this PR in favor of #5607

**Pull request closed without merging**
