### PR TITLE
fixed broken link to documentation basics in error message

### PR DESCRIPTION
**Pull request by baywet**
No login callback exceptions are providing a broken link, this PR fixes the links

### CODE REVIEW

**Comment by sameerag** [comment]
@baywet Thanks for bringing this up to our notice. This has to be fixed in the code rather and not in the documentation. We will be following up on this soon.

**Comment by sameerag** [comment]
#732 fixes this. Closing this PR.

**Comment by baywet** [comment]
@sameerag my PR included the code fixes as well :/

**Comment by sameerag** [comment]
@baywet I am so sorry. Guess I overlooked. :(. Will merge this later today.

**Pull request merged**
