### PR TITLE
fix: remove dist and docs folders from repository

### PR DESCRIPTION
**Pull request by zamzowd**
These folders are created as part of the build, and shouldn't be
included in the repository.

### CODE REVIEW

**Comment by Dedme** [comment]
i found it strange they existed.
it makes simple pull requests 10K lines of changes.

**Comment by zamzowd** [comment]
@Dedme For my pull requests, I just excluded these files from any commits.  That means the repo's dist and docs would be out of sync with the source code, but that shouldn't matter if the developer rebuilds the source.  Still, I'm hoping this gets accepted just to clean up the repo and make things a little less involved for contributors.

**Comment by sameerag** [comment]
@zamzowd  Thanks for the contribution.

We want to remove dist too from some time, and we are trying to get rid of the dependencies existed in the legacy test code before we do this. docs, we are still trying to find a way to have them in sync with the repo without pushing it in every commit. Hence I cannot commit for docs but dist will eventually go. This activity will be a part of the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) @navyasric  published.

**Comment by DarylThayil** [comment]
I think this is a great idea, I am all for removing generated files from the repo and cleaning up pull requests. 

I think the problem we need to solve before removing docs are that we have links in our ReadMe to our actual docs source in the repo. We probably want to put these docs somewhere else completely, and have them build and push on pull request merge. If we simply remove them now, we will have out of sync / broken links to docs for merged pull requests.

Like @sameerag  said @navyasric  has this as a part of the roadmap for the library and so we will hopefully have an opportunity to make this better soon.

**Comment by zamzowd** [comment]
I understand the need for docs to be stored *somewhere*.  As described, would expect a CI pipeline to run a build and store the dist and docs somewhere other than in the source control.

Feel free to close/reject this PR, assuming that the work on that automated build and artifacts storage will include removing the artifacts from the repo anyway.

(In the meantime, I'd like to plug #541 to try to get eyes on that, as it is allowing SSO behavior important to my project.)

**Comment by sameerag** [comment]
Closing this OR as removing /dist will be a part of the next release. Removing /docs is something we want to strategize more carefully, there is work on getting the comments up to date and then evaluating the documentation.

Please also refer #293 for some of the latest comments on this topic.

**Pull request closed without merging**
