### PR TITLE
Allow applications to disable postLogoutRedirectUri in MSAL Browser

### LINKED ISSUE #2145: How to disable post-logout redirect
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
The default logout behavior redirects users back to the current location.href. This doesn't work for my app because if a user is not authenticated we auto redirect users to login creating a confusing UX on logout. Instead, I would like to not redirect the user at all after the logout is successful. How can I disable the default redirect behavior? I've tried setting the msal config `postLogoutRedirectUri: ''` without success. 
I believe our current auth solution achieves this behavior by simply not providing the redirect param.

### PR DESCRIPTION
**Pull request by jasonnutter**
Today MSAL Browser will fallback to the current page for teh `postLogoutRedirectUri`, which prevents applications from opting out of that behavior. This PR adds the ability to set `postLogoutRedirectUri` to `null` (in the logout request or in the configuration) to prevent setting a `post_logout_redirect_uri` on the logout request.

### CODE REVIEW

**Review by tnorling — APPROVED** [review]
Looks good. Would this potentially be a breaking change for people who are not providing a `postLogoutRedirectUri` explicitly today? Is patch the right designation?

**Comment by jasonnutter** [comment]
@tnorling I can see that argument, however, I would say that the inability to not set a post logout redirect URI is a bug. I suppose one way we could make this somewhat backwards compatible is to make it so that setting `null` as the `postLogoutRedirectURI` (which I doubt anyone is doing today) is the way to turn off the post logout redirect.

**Comment by tnorling** [comment]
@jasonnutter I think I would slightly prefer `null` over empty string, however, either approaches are fine. I would also be fine with making this a minor version update and calling this out as "potentially breaking".

**Review by pkanher617 — APPROVED** [review]
I agree that we should probably call this out as a breaking change, I am fine with doing it as a minor version. If we opt to make this backwards compatible instead (which might be a better option here) I think I would prefer using `null`.

**Comment by jasonnutter** [comment]
Updated to make non-breaking: you must explicitly pass `null` to disable post logout redirect.

**Review by jo-arroyo — APPROVED** [review]

**Review by pkanher617 — APPROVED** [review]

**Comment by manavsharmaprog** [comment]
Found this fix after a lot of Google search.

> May I please request you to bring the documentation up to speed with this small trick of passing **null** in postlogoutredirecturi.


My use case was that I was logging out and got redirected back to login screen which caused the interaction_in_progress to be set and giving me an error on Chrome Dev console. Clearing the cookie manually didn't look like a good idea either.
I know there're some better ways to handle redirects but a lot of people may end up bumping into a similar use case as mine.

**Pull request merged**
