### PR TITLE
Request For Comment: Example Build Cleanup

### PR DESCRIPTION
**Pull request by DarylThayil**
DO NOT MERGE
This is a Work In Progress / Example of what we can do to improve / clean up our build

# Problems this solves
* Commiting Build Artifacts [lib-commonjs, lib-es6] 
* Building Unnecessary Artifacts [lib-es6]

I only cleaned up code build artifacts, I did not clean up the build for dist/ or docs

# What this does
* Run Build on Prepublish step 
* Only build a single es5 output that can be imported [ with typings and sourcemaps ] Should we have sourcemaps? Probably not ... 
* Ignore built files in git 
* Ignore src files in npm published lib

# What needs to still be done
* Make sure this works 🤷‍♂️ test it
* Adapt build / publish pipeline to new flow
* Add pushing dist to cd on build / publish (post publish)

### CODE REVIEW

**Comment by zamzowd** [comment]
Rather than a parameter on the npm script `"build:modules": "tsc --outDir lib"`, can update the `tsconfig.json` to have option `"outDir": "lib"` and have the npm script simply `"build:modules": "tsc"`.

In fact, can get rid of `build:modules` script altogether and have:
```
"build": "npm run clean && npm run doc && tsc && webpack && grunt && npm test"
```

I'm def in favor of removing build artifacts from the repo (#542).  However, I don't know enough about javascript modules to know the difference between the commonjs build and the es6 build.  My uses of the library have been on the commonjs build.

**Comment by DarylThayil** [comment]
@zamzowd  The recommendation to use tsconfig is great, will update when I go to productionalize this pr. 

I think the reason I like having a build:modules and in my other pr build:webapack, are because:
1. Sometimes you want to be able to run these scripts independent of eachother developing
2. the implementation of what building modules can change over time and be used why whatever script needs it
3. I want to break that build script apart.  I think things like test and lint should all be separate commands that you run in a build pipeline to be able to better isolate issues. 


In terms of the build artifacts, from what I understand in the published library that gets pushed to npm, the main export is defined in package json.  In the current setup this points to lib-commonjs/index, so consumers of this library are not even using lib-es6, or if they are they are doing so by reaching into folders.

The benefit of using lib es6 is probably lost on me if there is a benefit, so I am open to hearing them.  
This is a browser library only, so it will be used in one of 2 ways:
1. the msal.min.js (I think getting rid of the unminified version could make sense too) is imported in the html body.  This is already es5 code.
2.  the msal library is imported into a large application which may or may not be using es6. but will get the code from lib-commonjs.  Even if they reach in for the es6 code (which is unnecessary because es5 has sourcemaps and is the fully functioning version of the es6 code) when they build their application into a .js file for the browser to consume, it will all be compiled to es5 code. While browsers do have better and better support for es6, es5 is the lowest common denominator.

**Comment by zamzowd** [comment]
Something more to consider:

Right now, the folder containing msal-angular, msal-angularjs, and msal-core is called `lib`.  It might be syntactically confusing to also have a folder created by the build called `lib`.

Maybe can have tsc (commonjs) compile to `dist/commonjs` and webpack compile to `dist/bundles`, or something like that.

**Comment by sameerag** [comment]
@zamzowd this is something even we are considering. We will come up with an appropriate space for angular once we are done with our current core enhancements. We want to plan this with future implementations of other frameworks in consideration.

**Pull request closed without merging**
