### PR TITLE
chore: bump Playwright to 1.28

### PR DESCRIPTION
**Pull request by mxschmitt**
Context: https://github.com/microsoft/playwright/issues/19246

drive-by: remove `playwright` dependency, since this installs all the 3 Playwright browsers as well which you don't need.

It was locally for me working on the https://github.com/microsoft/playwright/issues/18928#issuecomment-1322468572 branch.

### CODE REVIEW

**Comment by hectormmg** [comment]
@mxschmitt thanks for the PR, we'll take a look and get try to get it merged!

**Comment by mxschmitt** [comment]
Would be helpful if we could run the e2e tests on this PR to verify nothing regressed.

Thanks!

**Review by derisen — APPROVED** [review]
thansk @mxschmitt -not sure why CI is skipping E2E tests, but they ran fine locally cc @hectormmg

**Comment by hectormmg** [comment]
> thansk @mxschmitt Max Schmitt FTE -not sure why CI is skipping E2E tests, but they ran fine locally cc @hectormmg Hector Morales FTE

CI checks are blocked on external PRs for security reasons, we have to manually authorize them

**Review by hectormmg — APPROVED** [review]

**Comment by tnorling** [comment]
> > thansk @mxschmitt Max Schmitt FTE -not sure why CI is skipping E2E tests, but they ran fine locally cc @hectormmg Hector Morales FTE
> 
> CI checks are blocked on external PRs for security reasons, we have to manually authorize them

You can pull this into a "staging" branch and open a new PR to dev to allow the E2E tests to run

**Comment by tnorling** [comment]
Closing in favor of #5470 which includes these changes

**Pull request closed without merging**
