### PR TITLE
React survey readme

### PR DESCRIPTION
**Pull request by ShannonCanTech**
React survey added to README.md.

Thanks Jason for letting me know to add additional surveys to sub MSAL.js libraries.

### CODE REVIEW

**Comment by jasonnutter** [comment]
Do you want to close your other PR? And only MSAL React, or would you like to add the surveys to the other libraries in the `lib` folder?

**Comment by ShannonCanTech** [comment]
> Do you want to close your other PR? And only MSAL React, or would you like to add the surveys to the other libraries in the `lib` folder?

I need all changes made to each of the README.md files to include the survey. Would you rather me do one massive PR of all the updates?

**Comment by jasonnutter** [comment]
> > Do you want to close your other PR? And only MSAL React, or would you like to add the surveys to the other libraries in the `lib` folder?
> 
> I need all changes made to each of the README.md files to include the survey. Would you rather me do one massive PR of all the updates?

@ShannonCanTech Yeah, one PR for all the libraries would be great. Thanks!

**Comment by jasonnutter** [comment]
@ShannonCanTech What is the status on this PR?

**Pull request closed without merging**
