### PR TITLE
Increase the number of retries for e2e tests

### PR DESCRIPTION
**Pull request by konstantin-msft**
- Increase the number of retries for e2e tests to mitigate VM resource contention.

### CODE REVIEW

**Comment by hectormmg** [comment]
Lgtm, just curious, how easy is it to see how many retries actually had to be done on a test run?

**Review by hectormmg — APPROVED** [review]

**Comment by hectormmg** [comment]
Also, this PR is a great reminder of why we should try to leverage constants like RETRY_TIMES everywhere. If we'd had a constant there from the beginning this PR could've had 50 less files.

**Review by derisen — APPROVED** [review]
LGTM -thanks for doing this!

**Review by sameerag — APPROVED** [review]
Does this increase our CI/CD time? Approving, but would like to see if the effect if this helped with the success rate vs time.

**Comment by tnorling** [comment]
> Does this increase our CI/CD time? Approving, but would like to see if the effect if this helped with the success rate vs time.

Reliability > Perf in a vacuum but I'm actually more concerned about the impact to queue time for other PRs when one PR is hogging the VMs our CI runs on. I've asked Konstantin to look into ways to minimize that impact (such as skipping E2E until the PR has been approved, making E2E a last step before merging)

**Comment by hectormmg** [comment]
> > Does this increase our CI/CD time? Approving, but would like to see if the effect if this helped with the success rate vs time.
> 
> Reliability > Perf in a vacuum but I'm actually more concerned about the impact to queue time for other PRs when one PR is hogging the VMs our CI runs on. I've asked Konstantin to look into ways to minimize that impact (such as skipping E2E until the PR has been approved, making E2E a last step before merging)

We can certainly take this offline, I will say one downside is that we'd need to be running the entire e2e test suite locally until the PR is approved for it to start catching any bugs the PR introduces.

**Comment by tnorling** [comment]
> We can certainly take this offline, I will say one downside is that we'd need to be running the entire e2e test suite locally until the PR is approved for it to start catching any bugs the PR introduces.

You can run workflows manually in Github as well if you're unsure and just want to do a quick check. I'm just worried that PRs that are still in active development will kick off a bunch of E2E tests on every commit which will fail 5 times and hold up the line. That said, if we can't find a middle ground right now I'm open to trying it and revisiting if/when it does become a problem.

**Comment by hectormmg** [comment]
> > We can certainly take this offline, I will say one downside is that we'd need to be running the entire e2e test suite locally until the PR is approved for it to start catching any bugs the PR introduces.
> 
> You can run workflows manually in Github as well if you're unsure and just want to do a quick check. I'm just worried that PRs that are still in active development will kick off a bunch of E2E tests on every commit which will fail 5 times and hold up the line. That said, if we can't find a middle ground right now I'm open to trying it and revisiting if/when it does become a problem.

No, I share that concern, I know it's the main reason we haven't done the retries yet. Maybe leaving E2E as a final step is the best compromise that still gives the team a better experience.

**Comment by konstantin-msft** [comment]
> Lgtm, just curious, how easy is it to see how many retries actually had to be done on a test run?

Analyzing logs for repetitive test names seems like the only option.

**Comment by konstantin-msft** [comment]
> > We can certainly take this offline, I will say one downside is that we'd need to be running the entire e2e test suite locally until the PR is approved for it to start catching any bugs the PR introduces.
> 
> You can run workflows manually in Github as well if you're unsure and just want to do a quick check. I'm just worried that PRs that are still in active development will kick off a bunch of E2E tests on every commit which will fail 5 times and hold up the line. That said, if we can't find a middle ground right now I'm open to trying it and revisiting if/when it does become a problem.

I would avoid running e2e jobs manually cause people can just forget about it. I would rather prefer kicking off e2e jobs when PR is ready for review. Please take a look at a follow-up PR https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5662.

**Comment by tnorling** [comment]
> I would avoid running e2e jobs manually cause people can just forget about it. I would rather prefer kicking off e2e jobs when PR is ready for review. Please take a look at a follow-up PR https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5662.

I agree, my suggestion to run the tests manually was more around if you want to verify the tests will pass _before_ you've gotten to the stage where tests will be auto-run by CI. It is an option in addition to, not instead of, auto-run CI tests which are required to merge the PR.

**Comment by konstantin-msft** [comment]
> Does this increase our CI/CD time? Approving, but would like to see if the effect if this helped with the success rate vs time.

It increases CI/CD time in case of a breaking change and/or VM resource contention. I am not sure I am aware of the way to capture CI/CD metrics you are referring to.

**Comment by hectormmg** [comment]
@konstantin-msft is there any way to limit the retries to tests that timeout? Other than the fact that there's less chance of ending up with long queuing times, I think it may be dangerous to have retries on all the time since it would prevent us from catching intermittent bugs.

**Review by peterzenz — APPROVED** [review]

**Comment by konstantin-msft** [comment]
> @konstantin-msft is there any way to limit the retries to tests that timeout? Other than the fact that there's less chance of ending up with long queuing times, I think it may be dangerous to have retries on all the time since it would prevent us from catching intermittent bugs.

You can do that locally by changing https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5649/files#diff-31e14e167d5f2968c7f301ff3197d4ff257f3f9bce6eeffd0fbc472784b861d0R11 param.

**Pull request merged**
