### PR TITLE
Use the v2.0 OpenID endpoint for a legacy authority

### PR DESCRIPTION
**Pull request by jkapil**

### CODE REVIEW

**Review by ss861 — APPROVED** [review]

**Review by ss861 — APPROVED** [review]
Approved.

**Review by hectormmg — APPROVED** [review]
LGTM!

**Comment by hectormmg** [comment]
@jkapil can you please run the beachball change command and push the changefile, thanks! https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md#beachball-check

**Comment by jkapil** [comment]
> @jkapil can you please run the beachball change command and push the changefile, thanks! https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md#beachball-check

Hye, does that needs to be run before pushing the changes. I get following results. 
> beachball:change
> beachball change --branch origin/dev

Checking for changes against "origin/dev"
fetching latest from remotes "origin/dev"
"@azure/node-token-validation" has a "none" change type, no version bump is required.
Skipping package dep validation - package @azure/node-token-validation has change type as none
Validating no private package among package dependencies
 OK!

No change files are needed

**Pull request closed without merging**
