### PR TITLE
Updated dependent MSAL package to 0.2.4 and msal-angular package to 0.1.3

### PR DESCRIPTION
**Pull request by amigup**
Since prior msal packages have hard coded prompt behavior of select_account and due to which in SSO flow,  login prompt always appear. Since the latest msal [0.2.4](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/v0.2.4) incorporate the appropriate prompt behavior so updated the package dependency in msal-angular to [0.2.4](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/v0.2.4). With the incorporated code change, the issue #629 will be fixed.

### CODE REVIEW

**Comment by mahi9984** [comment]
Hey everyone,

Please review this as this would help us out in going ahead with aadv2. And will also resolve the issue mentioned in PR.

**Comment by sameerag** [comment]
@amigup @mahi9984 Your PR looks fine but we are not planning any releases on angular as is since we want to upgrade it to msal-1.0.0 as soon as we can. Please find more details at: [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap).

**Comment by mahi9984** [comment]
@sameerag  In the roadmap I couldn't find dates for msal-angular. It shows upcoming. If you could help us out with the timelines for angular then it will help us in our planning.

**Comment by sameerag** [comment]
@mahi9984 One of us will reach out on this once we have the dates. It will also be updated in the roadmap once we have better clarity on the timelines. 

Apologies that I cannot give a response right now.

**Comment by DarylThayil** [comment]
@mahi9984  the tentative plan is that angular is updated to 1.0.0 mid summer, still working on dates, roadmap will be updated soon!

**Comment by DarylThayil** [comment]
@mahi9984  question, in the meantime can you install the version of msal 0.2.4 in your project deps so that msal angular uses that? Could be a stop gap for now. 
Concern is that 0.2.4 may have breaking changes that msal-angular is not ready to take. 
Closing this pr for now.

**Comment by DarylThayil** [comment]
reminder closing this because of planned angular work forthcoming

**Comment by mahi9984** [comment]
Thanks for providing the information.

**Pull request closed without merging**
