### PR TITLE
fix: updated to angular 7

### PR DESCRIPTION
**Pull request by Dedme**
Updated package to angular 7.1.2, including updating to rxjs 6.
All supporting applications being updated to latest version.

TSLint standards updated throughout codebase.
RXJS 6 implimentations of existing calls updated.
Import statments formatted for consistancy.

This update has updated the masl-angular project to be inline with the
lastest version of angular. The supporting packages have been updated
and many formatting changes have been made for consistancy.
The Sample package is out of date with the codebase as it wont work
without the lastest version of msal being in NPM. this will have its own
PR raised when appropriate.
I believe this is not completely compatible with Edge or IE still, as
there is other outstanding issues within the package, more PR's will be
raised for these issues also.

### CODE REVIEW

**Comment by danieladams456** [comment]
@nehaagrawal would you be able to review when you get a chance?
As a side note, would this PR be easier to review if the code formatting was postponed to a separate PR?

**Comment by pkanher617** [comment]
@danieladams456 @Dedme Thank you for your patience, I will be reviewing this PR later today. If possible, it would be very helpful to separate the code formatting into a separate PR. Thanks!

**Comment by Dedme** [comment]
thank you for taking action on this so fast.
> If possible, it would be very helpful to separate the code formatting into a separate PR.
i don't have time to get my hands on code for a little while, and it might take some time to rework this into 2 PR's. But if its too much in a single PR i can look at doing this towards the end of the month.

**Comment by frjtrifork** [comment]
@pkanher617 It has been two weeks since the last update about this long awaited PR. 
Would it be possible for you to accept the PR including the formatting?

The original "Support for Angular 6 " issue #421 was raised back in September. 
Blocking a PR that finally fixes this and supports Angular 7, solely due to code formatting is just plain sad for all of us waiting for this fix :-(

**Comment by danieladams456** [comment]
@hansmaad I just switched to using that as well, and really simplifies the client complexity.  No npm package needed, just trap denied API calls and redirect browser to login page.  I'm using it with [ALB built-in auth](https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/) so the backend just has to do authorization, not authentication.

**Comment by ruppert92** [comment]
Any updates on this? Over a week since the day or two notice.

**Comment by sameerag** [comment]
@ruppert92 , we seem to running into some issues in our testing when we combine @Dedme changes for Angular 7 support and some other build config changes we tried out for IE support. This will need a more careful integration. Hence we decided to hold off merging this to dev for now.

**Comment by navyasric** [comment]
Adding to @sameerag comment, based on discussion in the team, we recognize that the issues and feedback for preview version of Angular wrapper require further investigation and work. We are currently focused on addressing changes and improvements to the core MSAL.js library based on feedback.
Following this, we will target a release to address the Angular wrapper issues and requests. Please watch this [Roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap) for updates.

**Comment by JackEdwards** [comment]
Are there any updates on this issue, or any official workarounds to use in the meantime? As this is going to be used in prod I'd rather not use @Dedme solution yet if the team have found issues with it.

**Comment by frjtrifork** [comment]
> Are there any updates on this issue, or any official workarounds to use in the meantime? As this is going to be used in prod I'd rather not use @Dedme solution yet if the team have found issues with it.
Not to my knowledge. 
As @navyasric wrote the team is focusing on changing and improving the core library first. That work will result in a version 0.3 release of the msal js library. 
Once that is done, the next release on the roadmap is an update of the msal-angular / msal-angularjs.

On a side note - my current project is using the existing msal-angular library with Angular 7, and we have not experienced any issues. 
As far as I recall, the only thing I had to change back then was to add rxjs and rxjs-compat to my package.json
`
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.3.3",
`

**Comment by silver-stack** [comment]
> > Are there any updates on this issue, or any official workarounds to use in the meantime? As this is going to be used in prod I'd rather not use @Dedme solution yet if the team have found issues with it.
> 
> Not to my knowledge.
> As @navyasric wrote the team is focusing on changing and improving the core library first. That work will result in a version 0.3 release of the msal js library.
> Once that is done, the next release on the roadmap is an update of the msal-angular / msal-angularjs.
> 
> On a side note - my current project is using the existing msal-angular library with Angular 7, and we have not experienced any issues.
> As far as I recall, the only thing I had to change back then was to add rxjs and rxjs-compat to my package.json
> `"rxjs": "~6.3.3", "rxjs-compat": "^6.3.3",`

@frjtrifork I have tried updating rxjs and rxjs-compat also, and it is working in certain scenarios. 

My issue comes with ng build --prod, when I release a prod build in angular 7 I am getting null redirect URI passed back (see screenshot).  This does not happen on a normal dev build.

Secondly the dev builds appear to work fine on desktop, but are doing some odd stuff on Android chrome and Edge so have not persisted with these for now.

msal-angulat-7-error

**Comment by frjtrifork** [comment]
> > > Are there any updates on this issue, or any official workarounds to use in the meantime? As this is going to be used in prod I'd rather not use @Dedme solution yet if the team have found issues with it.
> > 
> > 
> > Not to my knowledge.
> > As @navyasric wrote the team is focusing on changing and improving the core library first. That work will result in a version 0.3 release of the msal js library.
> > Once that is done, the next release on the roadmap is an update of the msal-angular / msal-angularjs.
> > On a side note - my current project is using the existing msal-angular library with Angular 7, and we have not experienced any issues.
> > As far as I recall, the only thing I had to change back then was to add rxjs and rxjs-compat to my package.json
> > `"rxjs": "~6.3.3", "rxjs-compat": "^6.3.3",`
> 
> @frjtrifork I have tried updating rxjs and rxjs-compat also, and it is working in certain scenarios.
> 
> My issue comes with ng build --prod, when I release a prod build in angular 7 I am getting null redirect URI passed back (see screenshot). This does not happen on a normal dev build.
> 

I build the same way for production and don't have that issue.

I have specified the redirectUri for our different environments in environment.ts, environment.prod.ts, environment.staging.ts etc. files. 
When just doing `ng build`, the environment.ts file is used directly, and when doing `ng build --prod`, the environment.prod.ts file replaces the environment.ts file. (Configured in angular.json in the "configurations" section).

This is just a guess, but if you have done the same, a null redirectUri only when building for production could indicate that you have defined the redirectUri in only one of the files?

> Secondly the dev builds appear to work fine on desktop, but are doing some odd stuff on Android chrome and Edge so have not persisted with these for now.
> 
I have only used it for desktops, so I don't have any experience with msal on mobile browsers yet.

**Comment by frjtrifork** [comment]
Regarding the null redirectUri in production.

If you are using window.location to set the redirectUri in your msal configuration object dynamically then I think it is because of AOT you are getting null when making a production build.

See this issue for an explanation https://github.com/angular/angular-cli/issues/10957

We set static values for the redirectUri in different environment files that are replaced when building and that works, also with aot enabled.

/Flemming

On 14 Feb 2019, 22.53 +0100, silver-stack <notifications@github.com>, wrote:

Are there any updates on this issue, or any official workarounds to use in the meantime? As this is going to be used in prod I'd rather not use @Dedme<https://github.com/Dedme> solution yet if the team have found issues with it.

Not to my knowledge.
As @navyasric<https://github.com/navyasric> wrote the team is focusing on changing and improving the core library first. That work will result in a version 0.3 release of the msal js library.
Once that is done, the next release on the roadmap is an update of the msal-angular / msal-angularjs.

On a side note - my current project is using the existing msal-angular library with Angular 7, and we have not experienced any issues.
As far as I recall, the only thing I had to change back then was to add rxjs and rxjs-compat to my package.json
"rxjs": "~6.3.3", "rxjs-compat": "^6.3.3",

@frjtrifork<https://github.com/frjtrifork> I have tried updating rxjs and rxjs-compat also, and it is working in certain scenarios.

My issue comes with ng build --prod, when I release a prod build in angular 7 I am getting null redirect URI passed back (see screenshot). This does not happen on a normal dev build.

Secondly the dev builds appear to work fine on desktop, but are doing some odd stuff on Android chrome and Edge so have not persisted with these for now.

[msal-angulat-7-error]<https://user-images.githubusercontent.com/39124050/52820019-ba4db200-30a2-11e9-8d7a-18e5e3c4e67c.png>

**Comment by silver-stack** [comment]
> Regarding the null redirectUri in production. If you are using `window.location` to set the redirectUri in your msal configuration object dynamically then I think it is because of AOT you are getting null when making a production build. See this issue for an explanation [angular/angular-cli#10957](https://github.com/angular/angular-cli/issues/10957) In our project, we set static values for the redirectUri in different environment files that are replaced when building and that works, also with aot enabled. We only deploy to 3-4 different locations - so that is ok for us. There is also a request for supporting dynamic configuration in this msal issue that has some helpful comments - #481

I think you have hit the nail on the head, with this one.  We are indeed setting the following in our prod config:

```
    redirectUri:  window.location.origin + '/',
    postLogoutRedirectUri:  window.location.origin + '/',
```
We are not going live for about a month, so things like this have been a bit on the back burner, however it is a real help to find this out now.

I'll update our prod and test later today then report back.

**Comment by silver-stack** [comment]
@frjtrifork You were spot on with that tip off, I changed the window.location.origin to the full redirect URI for prod env and it worked a treat thank you.  Maybe I should have done some more research before writing it off ;)

Thanks again, I appreciate you taking the time to comment.

**Comment by ricklang** [comment]
Using the current msal-angular (0.1.2) with Angular 7.2.0. I added 'rxjs-compat' as [@frjtrifork](https://github.com/frjtrifork) mentioned. Everything seems to work fine on my local testing. When I deployed the application to Azure web services, the application stuck in a dead loop of Sign In page. Anybody has the same problem?

Also I tried to use 'popup: true' as others' suggested, but got running time error.

**Comment by frjtrifork** [comment]
> Using the current msal-angular (0.1.2) with Angular 7.2.0. I added 'rxjs-compat' as [@frjtrifork](https://github.com/frjtrifork) mentioned. Everything seems to work fine on my local testing. When I deployed the application to Azure web services, the application stuck in a dead loop of Sign In page. Anybody has the same problem?
> 
> Also I tried to use 'popup: true' as others' suggested, but got running time error.

If it works for you locally, then there should be no difference for a production environment except the configuration. Have you checked if your redirectUri is configured correctly for the production environment?
Also if an error is returned from azure when you start looping - that might also contain useful information for locating the issue. The error message is part of the URL redirect - I usually locate it using Chrome developer tools and inspect the network tab.

**Comment by infogulch** [comment]
There's a new [functioning workaround](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/481#issuecomment-471857627) to the `window.location` issue if anyone still cares.  It delays initialization of `Msal*` until after the page loads by providing it manually.  You return the config in a factory / arrow function, which means you can do whatever you want on-client before setting the config.

**Comment by Danieliverant** [comment]
any news on that?

**Comment by DanHitt** [comment]
Any news on this?

**Comment by sameerag** [comment]
Our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) is updated now with tentative dates for angular upgrade with our core library msal 1.0.0 changes. Please expect this feature to be a part of the same.

**Comment by jasonnutter** [comment]
Closing, as we'll be upgrading `msal-angular` to support the latest versions of Angular this quarter.

**Comment by nalyd2** [comment]
I have the following ==> error error: endpoint resolution error: endpoints cannot be resolved
What I have seen is that my authority changes to lowercase, the library converts to lowercase in the UserAgentApplication.js file

`UserAgentApplication.prototype.loginPopup = function (scopes, extraQueryParameters) {
        var _this = this;
        /*
        1. Create navigate url
        2. saves value in cache
        3. redirect user to AAD
         */
        return new Promise(function (resolve, reject) {
            if (_this._loginInProgress) {
                reject(Constants_1.ErrorCodes.loginProgressError + "|" + Constants_1.ErrorDescription.loginProgressError);
                return;
            }
            if (scopes) {
                var isValidScope = _this.validateInputScope(scopes);
                if (isValidScope && !Utils_1.Utils.isEmpty(isValidScope)) {
                    reject(Constants_1.ErrorCodes.inputScopesError + "|" + Constants_1.ErrorDescription.inputScopesError);
                    return;
                }
                scopes = _this.filterScopes(scopes);
            }
            else {
                scopes = [_this.clientId];
            }
            **var scope = scopes.join(" ").toLowerCase();**
            var popUpWindow = _this.openWindow("about:blank", "_blank", 1, _this, resolve, reject);
            if (!popUpWindow) {
                return;
            }
            _this._loginInProgress = true;
            _this.authorityInstance.ResolveEndpointsAsync().then(function () {
                var authenticationRequest = new AuthenticationRequestParameters_1.AuthenticationRequestParameters(_this.authorityInstance, _this.clientId, scopes, ResponseTypes.id_token, _this._redirectUri, _this._state);
                if (extraQueryParameters) {
                    authenticationRequest.extraQueryParameters = extraQueryParameters;
                }
                _this._cacheStorage.setItem(Constants_1.Constants.loginRequest, window.location.href);
                _this._cacheStorage.setItem(Constants_1.Constants.loginError, "");
                _this._cacheStorage.setItem(Constants_1.Constants.nonceIdToken, authenticationRequest.nonce);
                _this._cacheStorage.setItem(Constants_1.Constants.msalError, "");
                _this._cacheStorage.setItem(Constants_1.Constants.msalErrorDescription, "");
                var authorityKey = Constants_1.Constants.authority + Constants_1.Constants.resourceDelimeter + authenticationRequest.state;
                if (Utils_1.Utils.isEmpty(_this._cacheStorage.getItem(authorityKey))) {
                    _this._cacheStorage.setItem(authorityKey, _this.authority);
                }
                var urlNavigate = authenticationRequest.createNavigateUrl(scopes) + "&prompt=select_account" + "&response_mode=fragment";
                window.renewStates.push(authenticationRequest.state);
                window.requestType = Constants_1.Constants.login;
                _this.registerCallback(authenticationRequest.state, scope, resolve, reject);
                if (popUpWindow) {
                    _this._logger.infoPii("Navigated Popup window to:" + urlNavigate);
                    popUpWindow.location.href = urlNavigate;
                }
            }, function () {
                _this._logger.info(Constants_1.ErrorCodes.endpointResolutionError + ":" + Constants_1.ErrorDescription.endpointResolutionError);
                _this._cacheStorage.setItem(Constants_1.Constants.msalError, Constants_1.ErrorCodes.endpointResolutionError);
                _this._cacheStorage.setItem(Constants_1.Constants.msalErrorDescription, Constants_1.ErrorDescription.endpointResolutionError);
                if (reject) {
                    reject(Constants_1.ErrorCodes.endpointResolutionError + ":" + Constants_1.ErrorDescription.endpointResolutionError);
                }
                if (popUpWindow) {
                    popUpWindow.close();
                }
            }).catch(function (err) {
                _this._logger.warning("could not resolve endpoints");
                reject(err);
            });
        });
    };`

**Pull request closed without merging**
