### PR TITLE
Add SRI script for core

### PR DESCRIPTION
**Pull request by jasonnutter**
Core PR for #2487

### CODE REVIEW

**Review by pkanher617 — APPROVED** [review]
one thing to check is whether docs are updated if the upload fails.

**Review by tnorling — APPROVED** [review]
This is pretty cool! Would we be able to do something similar to update the version number in the Constants file?

**Review by sameerag — APPROVED** [review]

**Comment by jasonnutter** [comment]
> This is pretty cool! Would we be able to do something similar to update the version number in the Constants file?

Ah yeah forgot about that.

**Comment by jasonnutter** [comment]
I'll address the core version bump and better error handling incrementally in a follow up PR.

**Pull request merged**
