### PR TITLE
Set up CI with Azure Pipelines for Dev PRs

### PR DESCRIPTION
**Pull request by pkanher617**
This PR is to replace the CI product we are using with Azure Pipelines.

### CODE REVIEW

**Comment by pkanher617** [comment]
> Do we want to wait to remove travis until the ADO pipeline in functional? Also how are external submissions going to tested rather the test report shared? Travis today is public.

**Comment by pkanher617** [comment]
> Do we want to wait to remove travis until the ADO pipeline in functional? Also how are external submissions going to tested rather the test report shared? Travis today is public.

Just removing so that we don't have clutter, but eventually we are going to be moving away from travis, so this shouldn't be an issue.

**Comment by jasonnutter** [comment]
Would prefer not to have both...could we make part of the ADO viewable publicly? At least the pipeline status for a given PR.

**Comment by sameerag** [comment]
@jasonnutter yep! As long as someone who submits a PR can see the test reports.

**Comment by pkanher617** [comment]
Most contributors should have access to view test reports. We can verify before we merge this.

**Comment by jasonnutter** [comment]
Yep, looks like anyone can view the status (and the output). Looks good once you are able to get the build passing.

**Comment by pkanher617** [comment]
Moving to PR #912

**Pull request closed without merging**
