### PR TITLE
Add extra } for the msalInstance.handleRedirectPromise()

### PR DESCRIPTION
**Pull request by StefH**
Add extra } for the msalInstance.handleRedirectPromise()

### CODE REVIEW

**Review by jasonnutter — APPROVED** [review]

**Review by jo-arroyo — APPROVED** [review]

**Comment by jo-arroyo** [comment]
@StefH Thanks for catching this! Can you please run `npm run beachball:change` in the root of the repo and select change type None in order to generate change files? Thanks!

**Comment by StefH** [comment]
@jo-arroyo I tried to do `npm run beachball:change` however, I see that the CI still fails?

**Comment by jo-arroyo** [comment]
@StefH Can you discard/undo the changes to the package-lock files?

**Comment by StefH** [comment]
> 
> 
> @StefH Can you discard/undo the changes to the package-lock files?

I'm trying to fix that....

**Comment by StefH** [comment]
@jo-arroyo 
beachball should be fine, however it's strange that although I only change a doc file, I had to indicate that msal and msal-browser where not changed?

**Pull request merged**
