### PR TITLE
removed unneeded method definitions from controller interface

### PR DESCRIPTION
**Pull request by shoatman**
- Removed method definitions from the IController interface that did not belong there (Looks like doing so did not break any build.... will check the end 2 end tests to confirm)

### CODE REVIEW

**Review by tnorling — COMMENTED** [review]
You can probably remove `acquireTokenNative` and `acquireTokenByRefreshToken` from this as well. Those are implementation details.

Also changelog?

**Review by konstantin-msft — CHANGES_REQUESTED** [review]
These methods are used by the 1p library, please do not remove.

**Comment by shoatman** [comment]
> These methods are used by the 1p library, please do not remove.

Which methods?

**Comment by konstantin-msft** [comment]
> > These methods are used by the 1p library, please do not remove.
> 
> Which methods?

All of them

**Comment by tnorling** [comment]
Closing as a lot of this has been addressed and the remaining ones will be addressed

**Pull request closed without merging**
