### PR TITLE
AuthCode with Non-PKCE flow clients

### PR DESCRIPTION
**Pull request by noant**
Hi! We found that msal.js not works with non-pkce auth code flow. It means that I can't use msal.js and Chinese Azure Ad B2C, because now it accepts only implicit flow and auth code flow with client secret. So, to provide client secret we should call token endpoint through our custom endpoint with addiction of client secret. Net Core Web Api example:
```
        [HttpPost]
        [AllowAnonymous]
        public async Task<ObjectResult> ExchangeCn()
        {
            using (var sr = new StreamReader(HttpContext.Request.Body)) 
            {
                var requestBody = sr.ReadToEnd();
                
                if (!requestBody.Contains($"client_id=<clientId>"))
                    throw new HttpRequestException("Invalid client_id parameter");

                var extendedRequestBody = $"{requestBody}&client_secret=<clientSecret>";

                var tokenRequestContent = new StringContent(extendedRequestBody, Encoding.UTF8, "application/x-www-form-urlencoded");

                foreach (var header in HttpContext.Request.Headers.Where(x => x.Key.StartsWith("x-client")))
                    tokenRequestContent.Headers.Add(header.Key, header.Value.ToArray());


                using var client = HttpClientFactory.Create(new HttpClientHandler() { AllowAutoRedirect = true });
                var response = await client.PostAsync("https://<domain>.b2clogin.cn/<tenant>/b2c_1_sign_1_cn/oauth2/v2.0/token", tokenRequestContent);

                return new ObjectResult(await response.Content.ReadAsStringAsync());
            }
        }
```

I added some classes (AuthorizationCodeClientNonPkce, RefreshTokenClientNonPkce) that can be used to access to our custom endpoint instead of the token endpoint. Provider settings example:

```
export const config = {
    auth: {
        clientId: process.env.MSAL_CLIENT_ID,
        authority: SIGN_IN_AUTHORITY,
        redirectUri: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        navigateToLoginRequestUrl: false,
        nonPkceAuthCodeExchangeEndpoint: 'https://<my_custom_endpoint>/api/v1.2/auth/exchange_cn', <<< custom endpoint parameter
        useNonPkceAuthCodeExchangeEndpoint: true, <<< if true - use custom endpoint to exchange auth code to tokens
        knownAuthorities: ['https://<some_known_authority>']
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: !!window.document.documentMode, // true for IE
    },
    system: {
        loadFrameTimeout: 30000,
        // tokenRenewalOffsetSeconds: 0,
    },
};
```

I have already created my personal npm packages forked from msal-browser and msal-common because this functionality is very important to my organization.
https://www.npmjs.com/package/msal-common-ext
https://www.npmjs.com/package/msal-browser-ext
So in this branch, package.json in msal-browser refers to standard msal-common package and for msal-browser debugging, msal-common link should be changed to currently locally created msal-common package with new classes. In dev branch in my fork msal-browser already uses msal-common-ext package from npm.

### CODE REVIEW

**Comment by pkanher617** [comment]
@noant Currently we cannot accept this. MSAL.js is a moniker for multiple libraries, so I'm not sure which library you are using, but the two that are supported for Single-Page Application flows are the implicit flow ([@azure/msal](https://www.npmjs.com/package/@azure/msal) or [msal](https://www.npmjs.com/package/msal)) and the authorization code flow ([@azure/msal-browser](https://www.npmjs.com/package/@azure/msal-browser)). I want to reiterate, these are for browser-only flows, with no backend component. We cannot use Authorization Code Flow without PKCE because of the inherent security flaws that are exposed by browsers and mobile devices. You can read more about this [here](https://tools.ietf.org/html/rfc7636#section-1).

The .NET web API you are describing above does not fall under this. What you are probably looking for is our [@azure/msal-node](https://www.npmjs.com/package/@azure/msal-node) library, which is currently in alpha, and will be in public preview shortly. This will support the flows you are describing above (including auth code flow without PKCE).

**Comment by jasonnutter** [comment]
> It means that I can't use msal.js and Chinese Azure Ad B2C, because now it accepts only implicit flow and auth code flow with client secret.

Azure B2C should now support Auth Code Flow w/ PKCE for SPAs. Please open a support ticket if this does not appear to be working.

**Comment by noant** [comment]
> 
> 
> > It means that I can't use msal.js and Chinese Azure Ad B2C, because now it accepts only implicit flow and auth code flow with client secret.
> 
> Azure B2C should now support Auth Code Flow w/ PKCE for SPAs. Please open a support ticket if this does not appear to be working.

I already did it, but it did not affect anything =) I think I should choose another oauth service for my organization, because it is too many problems with azure b2c.

**Comment by jasonnutter** [comment]
Closing, as we will not be supported Auth Code without PKCE in MSAL Browser.

**Pull request closed without merging**
