### PR TITLE
Fix handling of multiple popup windows

### PR DESCRIPTION
**Pull request by jasonnutter**
This PR fixes the following bugs:

1. If the same app (using local storage) is opened in multiple tabs, only the first app instance is able to open a popup, due to temporary cache values being shared between tabs. This is addressed by moving temporary cache values to their own sessionStorage or memoryStorage instance so that they are not shared between tabs, and by setting a dynamic popup name so that the second tab won't try to open its url in the popup window opened by the first tab.
2. If an app invokes one of the popup APIs twice in a row without letting the first request finish, the popup for the first request will be broken, due to MSAL initially opening `about:blank` in the already opened popup (see #2614). This is fixed by moving the interaction in progress check above the code that initially opens the popup to `about:blank`.

There will be a follow up discussion about further enhancements we can make to the ergonomics of handling multiple concurrent popup requests.

### CODE REVIEW

**Review by tnorling — APPROVED** [review]
Should we add a couple E2E tests for these scenarios?

**Comment by jasonnutter** [comment]
> Should we add a couple E2E tests for these scenarios?

Looks like some e2e tests are broked, so may not need to add new ones.

**Review by pkanher617 — APPROVED** [review]
I also think we should add e2e tests (I'm not seeing where they are broken?)

**Comment by gabriel-kohen-by** [comment]
Hi Folks,

I'm using the libraries with the following versions:
```
    "@azure/msal-browser": "^2.12.0",
    "@azure/msal-react": "^1.0.0-beta.0"
```

The config object is:
```
const msalProviderConfig = {
  type: 'popup',
  msalConfig: {
    auth: {
      clientId,
      authority,
      knownAuthorities: [authority],
      redirectUri,
      postLogoutRedirectUri,
    },
    system: {
      loggerOptions: {
        loggerCallback: getLoggerCallback(),
      },
    },
  },
  silentRequestConfig: {
    scopes: [scopes, 'offline_access'],
  },
  endSessionRequestConfig: {},
  loginRequestConfig: {
    scopes: [scopes, 'offline_access'],
  },
};
```
Post logout redirect URL is `${window.location.origin}/` and redirectUrl is `redirectUri`
The as you can see seems to be failing intermittently. See the attached recording where all is working fine for several times until around the 50th second mark of the video the about:blank window stays hanging.
[Video clip recreating the issue](https://photos.app.goo.gl/A8oK5NQCPj21hYJr6)
Any idea what I'm might be doing wrong?
Thank you for the otherwise rock solid library.

@tnorling @jo-arroyo @jasonnutter @pkanher617

**Comment by tnorling** [comment]
@gabriel-kohen-by Can you please open an issue? Thanks!

**Pull request merged**
